---
- name: Uninstall Package
  hosts: all
  become: true  # Run tasks with elevated privileges (sudo)

  tasks:

    - name: Uninstall Package
      apt:
        name: nginx  # Change to the package you want to uninstall
        state: absent